/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceInfoRouteImport } from './routes/service-info'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ManualsRouteImport } from './routes/manuals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTsbRouteImport } from './routes/admin.tsb'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminMachinesRouteImport } from './routes/admin.machines'
import { Route as AdminDealersRouteImport } from './routes/admin.dealers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminTsbIndexRouteImport } from './routes/admin.tsb.index'
import { Route as DealerWarrantyRegistrationsRouteImport } from './routes/dealer.warranty.registrations'
import { Route as DealerWarrantyNewRouteImport } from './routes/dealer.warranty.new'
import { Route as DealerWarrantyDashboardRouteImport } from './routes/dealer.warranty.dashboard'
import { Route as AdminWarrantyDashboardRouteImport } from './routes/admin.warranty.dashboard'
import { Route as AdminWarrantyCertificatesRouteImport } from './routes/admin.warranty.certificates'
import { Route as AdminTsbNewRouteImport } from './routes/admin.tsb.new'
import { Route as AdminTsbDashboardRouteImport } from './routes/admin.tsb.dashboard'
import { Route as AdminTsbIdRouteImport } from './routes/admin.tsb.$id'

const ServiceInfoRoute = ServiceInfoRouteImport.update({
  id: '/service-info',
  path: '/service-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualsRoute = ManualsRouteImport.update({
  id: '/manuals',
  path: '/manuals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTsbRoute = AdminTsbRouteImport.update({
  id: '/admin/tsb',
  path: '/admin/tsb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMachinesRoute = AdminMachinesRouteImport.update({
  id: '/admin/machines',
  path: '/admin/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealersRoute = AdminDealersRouteImport.update({
  id: '/admin/dealers',
  path: '/admin/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTsbIndexRoute = AdminTsbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTsbRoute,
} as any)
const DealerWarrantyRegistrationsRoute =
  DealerWarrantyRegistrationsRouteImport.update({
    id: '/dealer/warranty/registrations',
    path: '/dealer/warranty/registrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const DealerWarrantyNewRoute = DealerWarrantyNewRouteImport.update({
  id: '/dealer/warranty/new',
  path: '/dealer/warranty/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerWarrantyDashboardRoute = DealerWarrantyDashboardRouteImport.update({
  id: '/dealer/warranty/dashboard',
  path: '/dealer/warranty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarrantyDashboardRoute = AdminWarrantyDashboardRouteImport.update({
  id: '/admin/warranty/dashboard',
  path: '/admin/warranty/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWarrantyCertificatesRoute =
  AdminWarrantyCertificatesRouteImport.update({
    id: '/admin/warranty/certificates',
    path: '/admin/warranty/certificates',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTsbNewRoute = AdminTsbNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTsbRoute,
} as any)
const AdminTsbDashboardRoute = AdminTsbDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminTsbRoute,
} as any)
const AdminTsbIdRoute = AdminTsbIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTsbRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/manuals': typeof ManualsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/service-info': typeof ServiceInfoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tsb': typeof AdminTsbRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
  '/admin/tsb/$id': typeof AdminTsbIdRoute
  '/admin/tsb/dashboard': typeof AdminTsbDashboardRoute
  '/admin/tsb/new': typeof AdminTsbNewRoute
  '/admin/warranty/certificates': typeof AdminWarrantyCertificatesRoute
  '/admin/warranty/dashboard': typeof AdminWarrantyDashboardRoute
  '/dealer/warranty/dashboard': typeof DealerWarrantyDashboardRoute
  '/dealer/warranty/new': typeof DealerWarrantyNewRoute
  '/dealer/warranty/registrations': typeof DealerWarrantyRegistrationsRoute
  '/admin/tsb/': typeof AdminTsbIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/manuals': typeof ManualsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/service-info': typeof ServiceInfoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases': typeof CasesIndexRoute
  '/admin/tsb/$id': typeof AdminTsbIdRoute
  '/admin/tsb/dashboard': typeof AdminTsbDashboardRoute
  '/admin/tsb/new': typeof AdminTsbNewRoute
  '/admin/warranty/certificates': typeof AdminWarrantyCertificatesRoute
  '/admin/warranty/dashboard': typeof AdminWarrantyDashboardRoute
  '/dealer/warranty/dashboard': typeof DealerWarrantyDashboardRoute
  '/dealer/warranty/new': typeof DealerWarrantyNewRoute
  '/dealer/warranty/registrations': typeof DealerWarrantyRegistrationsRoute
  '/admin/tsb': typeof AdminTsbIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/manuals': typeof ManualsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/service-info': typeof ServiceInfoRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tsb': typeof AdminTsbRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/cases/$id': typeof CasesIdRoute
  '/cases/': typeof CasesIndexRoute
  '/admin/tsb/$id': typeof AdminTsbIdRoute
  '/admin/tsb/dashboard': typeof AdminTsbDashboardRoute
  '/admin/tsb/new': typeof AdminTsbNewRoute
  '/admin/warranty/certificates': typeof AdminWarrantyCertificatesRoute
  '/admin/warranty/dashboard': typeof AdminWarrantyDashboardRoute
  '/dealer/warranty/dashboard': typeof DealerWarrantyDashboardRoute
  '/dealer/warranty/new': typeof DealerWarrantyNewRoute
  '/dealer/warranty/registrations': typeof DealerWarrantyRegistrationsRoute
  '/admin/tsb/': typeof AdminTsbIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/manuals'
    | '/reset-password'
    | '/service'
    | '/service-info'
    | '/admin/dashboard'
    | '/admin/dealers'
    | '/admin/machines'
    | '/admin/settings'
    | '/admin/tsb'
    | '/admin/users'
    | '/cases/$id'
    | '/cases/'
    | '/admin/tsb/$id'
    | '/admin/tsb/dashboard'
    | '/admin/tsb/new'
    | '/admin/warranty/certificates'
    | '/admin/warranty/dashboard'
    | '/dealer/warranty/dashboard'
    | '/dealer/warranty/new'
    | '/dealer/warranty/registrations'
    | '/admin/tsb/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/manuals'
    | '/reset-password'
    | '/service'
    | '/service-info'
    | '/admin/dashboard'
    | '/admin/dealers'
    | '/admin/machines'
    | '/admin/settings'
    | '/admin/users'
    | '/cases/$id'
    | '/cases'
    | '/admin/tsb/$id'
    | '/admin/tsb/dashboard'
    | '/admin/tsb/new'
    | '/admin/warranty/certificates'
    | '/admin/warranty/dashboard'
    | '/dealer/warranty/dashboard'
    | '/dealer/warranty/new'
    | '/dealer/warranty/registrations'
    | '/admin/tsb'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/manuals'
    | '/reset-password'
    | '/service'
    | '/service-info'
    | '/admin/dashboard'
    | '/admin/dealers'
    | '/admin/machines'
    | '/admin/settings'
    | '/admin/tsb'
    | '/admin/users'
    | '/cases/$id'
    | '/cases/'
    | '/admin/tsb/$id'
    | '/admin/tsb/dashboard'
    | '/admin/tsb/new'
    | '/admin/warranty/certificates'
    | '/admin/warranty/dashboard'
    | '/dealer/warranty/dashboard'
    | '/dealer/warranty/new'
    | '/dealer/warranty/registrations'
    | '/admin/tsb/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ManualsRoute: typeof ManualsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceRoute: typeof ServiceRoute
  ServiceInfoRoute: typeof ServiceInfoRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDealersRoute: typeof AdminDealersRoute
  AdminMachinesRoute: typeof AdminMachinesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTsbRoute: typeof AdminTsbRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  CasesIdRoute: typeof CasesIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
  AdminWarrantyCertificatesRoute: typeof AdminWarrantyCertificatesRoute
  AdminWarrantyDashboardRoute: typeof AdminWarrantyDashboardRoute
  DealerWarrantyDashboardRoute: typeof DealerWarrantyDashboardRoute
  DealerWarrantyNewRoute: typeof DealerWarrantyNewRoute
  DealerWarrantyRegistrationsRoute: typeof DealerWarrantyRegistrationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service-info': {
      id: '/service-info'
      path: '/service-info'
      fullPath: '/service-info'
      preLoaderRoute: typeof ServiceInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manuals': {
      id: '/manuals'
      path: '/manuals'
      fullPath: '/manuals'
      preLoaderRoute: typeof ManualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tsb': {
      id: '/admin/tsb'
      path: '/admin/tsb'
      fullPath: '/admin/tsb'
      preLoaderRoute: typeof AdminTsbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/machines': {
      id: '/admin/machines'
      path: '/admin/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dealers': {
      id: '/admin/dealers'
      path: '/admin/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AdminDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tsb/': {
      id: '/admin/tsb/'
      path: '/'
      fullPath: '/admin/tsb/'
      preLoaderRoute: typeof AdminTsbIndexRouteImport
      parentRoute: typeof AdminTsbRoute
    }
    '/dealer/warranty/registrations': {
      id: '/dealer/warranty/registrations'
      path: '/dealer/warranty/registrations'
      fullPath: '/dealer/warranty/registrations'
      preLoaderRoute: typeof DealerWarrantyRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/warranty/new': {
      id: '/dealer/warranty/new'
      path: '/dealer/warranty/new'
      fullPath: '/dealer/warranty/new'
      preLoaderRoute: typeof DealerWarrantyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/warranty/dashboard': {
      id: '/dealer/warranty/dashboard'
      path: '/dealer/warranty/dashboard'
      fullPath: '/dealer/warranty/dashboard'
      preLoaderRoute: typeof DealerWarrantyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warranty/dashboard': {
      id: '/admin/warranty/dashboard'
      path: '/admin/warranty/dashboard'
      fullPath: '/admin/warranty/dashboard'
      preLoaderRoute: typeof AdminWarrantyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/warranty/certificates': {
      id: '/admin/warranty/certificates'
      path: '/admin/warranty/certificates'
      fullPath: '/admin/warranty/certificates'
      preLoaderRoute: typeof AdminWarrantyCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tsb/new': {
      id: '/admin/tsb/new'
      path: '/new'
      fullPath: '/admin/tsb/new'
      preLoaderRoute: typeof AdminTsbNewRouteImport
      parentRoute: typeof AdminTsbRoute
    }
    '/admin/tsb/dashboard': {
      id: '/admin/tsb/dashboard'
      path: '/dashboard'
      fullPath: '/admin/tsb/dashboard'
      preLoaderRoute: typeof AdminTsbDashboardRouteImport
      parentRoute: typeof AdminTsbRoute
    }
    '/admin/tsb/$id': {
      id: '/admin/tsb/$id'
      path: '/$id'
      fullPath: '/admin/tsb/$id'
      preLoaderRoute: typeof AdminTsbIdRouteImport
      parentRoute: typeof AdminTsbRoute
    }
  }
}

interface AdminTsbRouteChildren {
  AdminTsbIdRoute: typeof AdminTsbIdRoute
  AdminTsbDashboardRoute: typeof AdminTsbDashboardRoute
  AdminTsbNewRoute: typeof AdminTsbNewRoute
  AdminTsbIndexRoute: typeof AdminTsbIndexRoute
}

const AdminTsbRouteChildren: AdminTsbRouteChildren = {
  AdminTsbIdRoute: AdminTsbIdRoute,
  AdminTsbDashboardRoute: AdminTsbDashboardRoute,
  AdminTsbNewRoute: AdminTsbNewRoute,
  AdminTsbIndexRoute: AdminTsbIndexRoute,
}

const AdminTsbRouteWithChildren = AdminTsbRoute._addFileChildren(
  AdminTsbRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ManualsRoute: ManualsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceRoute: ServiceRoute,
  ServiceInfoRoute: ServiceInfoRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDealersRoute: AdminDealersRoute,
  AdminMachinesRoute: AdminMachinesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTsbRoute: AdminTsbRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  CasesIdRoute: CasesIdRoute,
  CasesIndexRoute: CasesIndexRoute,
  AdminWarrantyCertificatesRoute: AdminWarrantyCertificatesRoute,
  AdminWarrantyDashboardRoute: AdminWarrantyDashboardRoute,
  DealerWarrantyDashboardRoute: DealerWarrantyDashboardRoute,
  DealerWarrantyNewRoute: DealerWarrantyNewRoute,
  DealerWarrantyRegistrationsRoute: DealerWarrantyRegistrationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
